### ISSUE TITLE
Stan code

### ISSUE THREAD

**Issue by aakhmetz** [jwatowatson/Determinants-viral-clearance#1]
Dear authors,

Thank for your interesting study - I wonder if it would be possible to share the stan scripts as ".stan" files. It is a bit too difficult to check rds files without downloading and using R environment, which is not so convenient.

-Andrei R. Akhmetzhanov

**Comment by jwatowatson** [comment]
The .stan files are in the folder Stan_models. Can you not see them?

**Comment by aakhmetz** [comment]
Ah, I apologies - my mistake. My browser cut some filenames, and when I clicked several times, it was a .rds file.
